language: c++
sudo: false

before_install:
  - sudo apt-get update
  - sudo apt-get install -y
addons:
  apt:
    packages:
    - cmake
    - libopenmpi-dev
    - openmpi-bin
    - openmpi-common
    - libglu1-mesa
    - libpng-dev
    - libfontconfig1-dev

notifications:
  email:
    on_success: never
    on_failure: always